spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gptchat-1
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/gptchat-1
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:db/migration

server:
  port: 8089
  servlet:
    context-path: /gptchat-1


gpt:
  api:
    url: https://api.openai.com
    key: your_api_key

logging:
  level:
    root: INFO
    org:
      flywaydb: DEBUG
