spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gpt-chat-v2
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
flyway:
  locations: classpath:db/migration

server:
  port: 8089
  servlet:
    context-path: /gptchat-1
